import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { optimizeSvg } from "./index.js";

function fixture(name: string): string {
  return readFileSync(fileURLToPath(new URL(`./__fixtures__/${name}`, import.meta.url)), "utf8");
}

function rootFixture(name: string): string {
  return readFileSync(fileURLToPath(new URL(`../../../fixtures/${name}`, import.meta.url)), "utf8");
}

describe("optimizeSvg safe passes", () => {
  it("removes XML comments", () => {
    const result = optimizeSvg(fixture("comments.svg"));

    expect(result.svg).not.toContain("generated by a design tool");
    expect(result.svg).toBe('<svg width="24" height="24"><rect width="12" height="12.5"/></svg>');
  });

  it("removes metadata when enabled", () => {
    const result = optimizeSvg(fixture("metadata.svg"), { precision: 2, removeMetadata: true });

    expect(result.svg).toBe('<svg width="24" height="24"><rect width="12" height="12"/></svg>');
  });

  it("keeps metadata when disabled", () => {
    const result = optimizeSvg(fixture("metadata.svg"), { precision: 2, removeMetadata: false });
    const defaultResult = optimizeSvg(fixture("metadata.svg"), { precision: 2 });

    expect(result.svg).toBe(
      '<svg width="24" height="24"><metadata>exported metadata</metadata><rect width="12" height="12"/></svg>'
    );
    expect(defaultResult.svg).toBe(result.svg);
  });

  it("sorts attributes deterministically", () => {
    const result = optimizeSvg(fixture("attribute-sorting.svg"), { precision: 2 });

    expect(result.svg).toBe(
      '<svg viewBox="0 0 10 10" width="10" height="10" aria-label="icon" data-z="z"></svg>'
    );
  });

  it("normalizes numeric precision conservatively", () => {
    const result = optimizeSvg(fixture("numeric-precision.svg"), { precision: 2 });

    expect(result.svg).toBe(
      '<svg viewBox="0 0 24.5 24.12"><rect width="10" height="10.56" data-id="box-10.5000"/></svg>'
    );
  });

  it("does not remove risky SVG features in V0", () => {
    const result = optimizeSvg(fixture("risky-features.svg"), { precision: 2 });

    expect(result.svg).toContain("<defs>");
    expect(result.svg).toContain("<linearGradient");
    expect(result.svg).toContain("<clipPath");
    expect(result.svg).toContain("<symbol");
    expect(result.svg).toContain("<style>.primary { fill: url(#paint); stroke-width: 1.5000; }</style>");
    expect(result.svg).toContain('d="M0.0000 0.0000 L24.0000 0.0000 L24.0000 24.0000 Z"');
    expect(result.svg).toContain('fill="url(#paint)"');
    expect(result.svg).toContain('clip-path="url(#clip)"');
  });

  it("returns pass reports", () => {
    const result = optimizeSvg(fixture("metadata.svg"), { precision: 2, removeMetadata: true });

    expect(result.reports.map((report) => report.name)).toEqual([
      "removeComments",
      "removeMetadata",
      "normalizeNumbers",
      "sortAttributesDeterministically",
      "normalizeWhitespace"
    ]);
    expect(result.reports.map((report) => report.changed)).toEqual([false, true, false, false, true]);
    expect(result.reports.every((report) => report.beforeBytes >= report.afterBytes)).toBe(true);
    expect(result.beforeBytes).toBe(Buffer.byteLength(fixture("metadata.svg"), "utf8"));
    expect(result.afterBytes).toBe(Buffer.byteLength(result.svg, "utf8"));
    expect(result.savedBytes).toBe(result.beforeBytes - result.afterBytes);
  });

  it("returns deterministic and idempotent output bytes", () => {
    const input = fixture("attribute-sorting.svg");
    const first = optimizeSvg(input, { precision: 2 }).svg;
    const second = optimizeSvg(input, { precision: 2 }).svg;
    const third = optimizeSvg(first, { precision: 2 }).svg;

    expect(second).toBe(first);
    expect(third).toBe(first);
    expect(Buffer.from(second)).toEqual(Buffer.from(first));
    expect(Buffer.from(third)).toEqual(Buffer.from(first));
  });
});

describe("public fixture suite", () => {
  it("covers the basic SVG fixture", () => {
    const input = rootFixture("simple/basic.svg");
    const result = optimizeSvg(input, { precision: 2 });
    const withMetadataRemoval = optimizeSvg(input, { precision: 2, removeMetadata: true });

    expect(result.svg).not.toContain("generated by a design tool");
    expect(result.svg).toContain("<metadata>exported metadata</metadata>");
    expect(result.svg).toContain('d="M4 4 H20 V20 H4 Z"');
    expect(withMetadataRemoval.svg).not.toContain("<metadata>");
  });

  it("covers comments and metadata fixtures", () => {
    const comments = optimizeSvg(rootFixture("simple/comments.svg"), { precision: 2 }).svg;
    const metadata = optimizeSvg(rootFixture("simple/metadata.svg"), { precision: 2 }).svg;
    const metadataRemoved = optimizeSvg(rootFixture("simple/metadata.svg"), {
      precision: 2,
      removeMetadata: true
    }).svg;

    expect(comments).not.toContain("exported by icon tool");
    expect(metadata).toContain("<metadata>source file: icon.ai</metadata>");
    expect(metadataRemoved).not.toContain("<metadata>");
  });

  it("covers decimal number normalization without changing non-numeric attributes", () => {
    const result = optimizeSvg(rootFixture("simple/numbers-decimals.svg"), { precision: 2 }).svg;

    expect(result).toContain('viewBox="0 0 100 50.56"');
    expect(result).toContain('width="100"');
    expect(result).toContain('height="50.56"');
    expect(result).toContain('cx="10.12"');
    expect(result).toContain('cy="20.99"');
    expect(result).toContain('r="5.5"');
    expect(result).toContain('data-label="size-10.5000"');
  });

  it.each([
    {
      name: "gradients",
      file: "safety/gradient.svg",
      expected: ["<defs>", "<linearGradient", 'fill="url(#g)"']
    },
    {
      name: "masks",
      file: "safety/mask.svg",
      expected: ["<mask", 'id="fade"', 'mask="url(#fade)"']
    },
    {
      name: "clip paths",
      file: "safety/clip-path.svg",
      expected: ["<clipPath", 'id="clip"', 'clip-path="url(#clip)"']
    },
    {
      name: "symbols",
      file: "safety/symbol.svg",
      expected: ["<symbol", 'id="mark"', 'href="#mark"']
    },
    {
      name: "style attributes",
      file: "safety/style-attribute.svg",
      expected: ['style="fill: red; stroke-width: 1.5000; opacity: 0.7500"']
    },
    {
      name: "nested groups",
      file: "safety/nested-groups.svg",
      expected: ["<g", 'id="outer"', 'id="inner"', 'transform="translate(2 2)"']
    },
    {
      name: "path data",
      file: "safety/path-data.svg",
      expected: ['d="M4.0000 4.0000 C8.1250 2.5000 15.8750 2.5000 20.0000 4.0000"']
    }
  ])("preserves $name fixtures", ({ file, expected }) => {
    const result = optimizeSvg(rootFixture(file), { precision: 2 }).svg;

    for (const token of expected) {
      expect(result).toContain(token);
    }
  });

  it("keeps fixture output deterministic and idempotent", () => {
    const fixtureNames = [
      "simple/basic.svg",
      "simple/comments.svg",
      "simple/metadata.svg",
      "simple/numbers-decimals.svg",
      "safety/clip-path.svg",
      "safety/gradient.svg",
      "safety/mask.svg",
      "safety/nested-groups.svg",
      "safety/path-data.svg",
      "safety/style-attribute.svg",
      "safety/symbol.svg"
    ];

    for (const name of fixtureNames) {
      const input = rootFixture(name);
      const first = optimizeSvg(input, { precision: 2 }).svg;
      const second = optimizeSvg(input, { precision: 2 }).svg;
      const third = optimizeSvg(first, { precision: 2 }).svg;

      expect(second).toBe(first);
      expect(third).toBe(first);
    }
  });
});
