import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { optimizeSvg } from "./index.js";

function fixture(name: string): string {
  return readFileSync(fileURLToPath(new URL(`./__fixtures__/${name}`, import.meta.url)), "utf8");
}

describe("optimizeSvg safe passes", () => {
  it("removes XML comments", () => {
    const result = optimizeSvg(fixture("comments.svg"));

    expect(result.svg).not.toContain("generated by a design tool");
    expect(result.svg).toBe('<svg width="24" height="24"><rect width="12" height="12.5"/></svg>');
  });

  it("removes metadata when enabled", () => {
    const result = optimizeSvg(fixture("metadata.svg"), { precision: 2, removeMetadata: true });

    expect(result.svg).toBe('<svg width="24" height="24"><rect width="12" height="12"/></svg>');
  });

  it("keeps metadata when disabled", () => {
    const result = optimizeSvg(fixture("metadata.svg"), { precision: 2, removeMetadata: false });
    const defaultResult = optimizeSvg(fixture("metadata.svg"), { precision: 2 });

    expect(result.svg).toBe(
      '<svg width="24" height="24"><metadata>exported metadata</metadata><rect width="12" height="12"/></svg>'
    );
    expect(defaultResult.svg).toBe(result.svg);
  });

  it("sorts attributes deterministically", () => {
    const result = optimizeSvg(fixture("attribute-sorting.svg"), { precision: 2 });

    expect(result.svg).toBe(
      '<svg viewBox="0 0 10 10" width="10" height="10" aria-label="icon" data-z="z"></svg>'
    );
  });

  it("normalizes numeric precision conservatively", () => {
    const result = optimizeSvg(fixture("numeric-precision.svg"), { precision: 2 });

    expect(result.svg).toBe(
      '<svg viewBox="0 0 24.5 24.12"><rect width="10" height="10.56" data-id="box-10.5000"/></svg>'
    );
  });

  it("does not remove risky SVG features in V0", () => {
    const result = optimizeSvg(fixture("risky-features.svg"), { precision: 2 });

    expect(result.svg).toContain("<defs>");
    expect(result.svg).toContain("<linearGradient");
    expect(result.svg).toContain("<clipPath");
    expect(result.svg).toContain("<symbol");
    expect(result.svg).toContain("<style>.primary { fill: url(#paint); stroke-width: 1.5000; }</style>");
    expect(result.svg).toContain('d="M0.0000 0.0000 L24.0000 0.0000 L24.0000 24.0000 Z"');
    expect(result.svg).toContain('fill="url(#paint)"');
    expect(result.svg).toContain('clip-path="url(#clip)"');
  });

  it("returns pass reports", () => {
    const result = optimizeSvg(fixture("metadata.svg"), { precision: 2, removeMetadata: true });

    expect(result.reports.map((report) => report.name)).toEqual([
      "removeComments",
      "removeMetadata",
      "normalizeNumbers",
      "sortAttributesDeterministically",
      "normalizeWhitespace"
    ]);
    expect(result.reports.map((report) => report.changed)).toEqual([false, true, false, false, true]);
    expect(result.reports.every((report) => report.beforeBytes >= report.afterBytes)).toBe(true);
    expect(result.beforeBytes).toBe(Buffer.byteLength(fixture("metadata.svg"), "utf8"));
    expect(result.afterBytes).toBe(Buffer.byteLength(result.svg, "utf8"));
    expect(result.savedBytes).toBe(result.beforeBytes - result.afterBytes);
  });

  it("returns deterministic and idempotent output bytes", () => {
    const input = fixture("attribute-sorting.svg");
    const first = optimizeSvg(input, { precision: 2 }).svg;
    const second = optimizeSvg(input, { precision: 2 }).svg;
    const third = optimizeSvg(first, { precision: 2 }).svg;

    expect(second).toBe(first);
    expect(third).toBe(first);
    expect(Buffer.from(second)).toEqual(Buffer.from(first));
    expect(Buffer.from(third)).toEqual(Buffer.from(first));
  });
});
